config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies
  resources :actors
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :movies

  def age
    return Time.now.year - year_of_birth
  end
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :actors
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  def full_name (first_name, last_name)
   return first_name + " " + last_name
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

private
  def post_params
  params.require(:actor).permit(:name, :year_of_birth, :thumbnail)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end


private
  def post_params
  params.require(:movie).permit(:title, :summary, :youtube_embeded_id, :thumbnail)

  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/_form.html.erb
<% if @actor.errors.any? %>
  <% @actor.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for @actor do |f| %>
  <div class="input-group input-group-lg">
    <%= f.label :name, class: 'input-group-addon' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-lg">
    <%= f.label :year_of_birth, class: 'input-group-addon' %>
    <%= f.number_field :year_of_birth, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-lg">
    <%= f.label :thumbnail, class: 'input-group-addon' %>
    <%= f.text_field :thumbnail, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/actors/edit.html.erb
<h2 class="text-center">Editing <%= @actor.name %></h1>
<br>

<%= render 'form' %>

app/views/actors/new.html.erb
<h2 class="text-center">New Actor</h1>
<br>

<%= render 'form' %>

app/views/actors/show.html.erb
<h2 class='text-center'><%= @actor.name %></h2>
<hr>
<br>
<div class="row">
  <div class="text-center"><%= image_tag @actor.thumbnail %></div>
  <h4>Age:</h4>
  <p><%= @actor.age %></p>

  <h4>Movies:</h4>
  <% @actor.movies.each do |movie| %>
    <p><%= link_to movie.title, movie_path(movie) %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMDB</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">

  <!-- Static navbar -->
  <div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'IMDB', root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Movies', movies_path %></li>
          <li><%= link_to 'Create Movie', new_movie_path %></li>
          <li><%= link_to 'Create Actor', new_actor_path %></li>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </div>

  <!-- Main component for a primary marketing message or call to action -->
  <%= yield %>

</div> <!-- /container -->

</body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
  <% @movie.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for @movie do |f| %>
  <div class="input-group input-group-lg">
    <%= f.label :title, class: 'input-group-addon' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-lg">
    <%= f.label :summary, class: 'input-group-addon' %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-lg">
    <%= f.label :youtube_embed_id, class: 'input-group-addon' %>
    <%= f.text_field :youtube_embed_id, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-lg">
    <%= f.label :thumbnail, class: 'input-group-addon' %>
    <%= f.text_field :thumbnail, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/movies/edit.html.erb
<h2 class="text-center">Edit <%= @movie.title %></h1>
<br>

<%= render 'form' %>

app/views/movies/index.html.erb
<h2 class='text-center'>Our Current Movies</h2>
<hr>
<br>
<div class="row text-center">
  <% @movies.each do |movie| %>
    <div class="col-md-4">
      <%= link_to(image_tag(movie.thumbnail), movie_path(movie)) %>
      <p><%= movie.title %></p>
    </div>
<% end %>
</div>

app/views/movies/new.html.erb
<h2 class="text-center">New Movie</h1>
<br>

<%= render 'form' %>

app/views/movies/show.html.erb
<h2 class='text-center'><%= @movie.title %></h2>
<hr>
<br>
<div class="row">
  <div class="text-center">
    <iframe
      id="ytplayer"
      type="text/html"
      width="640"
      height="390"
      src="<%= "http://www.youtube.com/embed/#{@movie.youtube_embed_id}" %>"
      frameborder="0"
    /></iframe>
  </div>

  <h4>Summary:</h4>
  <p><%= @movie.summary %></p>

  <h4>Actors:</h4>
  <% @movie.actors.each do |actor| %>
    <p><%= link_to actor.name, actor_path(actor) %>, age: <%= actor.age %></p>
  <% end %>

  <h4>Reviews:</h4>
  <% @movie.reviews.each do |review| %>
    <p>By: <%= review.user.full_name %><br><%= review.body %></p>
  <% end %>
</div>